### ISSUE TITLE
More information in diaper change intent

### ISSUE THREAD

**Issue by btoconnor** [babybuddy/babybuddy-alexa-skill#6]
I'd like to be able to say "Alexa, record a Wet/Solid/Full diaper change" rather than have to go through a series of yes / no prompts each time.

I tried to add this myself (I have no experience with custom alexa skills, but willing to learn with some pointers) but I couldn't figure out how to get the skill to stop asking "Was it wet?" even if I commented out the `getSlotValue(...)` call.

I tried adding the extra samples to the `en-US.json` file, with a new diaper type  but nothing I tried stopped the question being asked.  Happy to provide my diff as-is or just simply accept pointers.

**Comment by cdubz** [comment]
@rplankenhorn any pointers or recommendations here?

**Comment by cdubz** [comment]
> * Move diaper contents to the additional questions dialog
> 
> * Handle diaper content handling in the initial invocation (ie, Alexa, tell Baby Buddy to record a wet diaper)
> 
> * Possibly move the set of questions to utilizing Amazon's built in `YesIntent` / `NoIntent` so that the skill here doesn't have to define custom yes / no types.  This is a little more complicated so I'm not sure I want to promise much there (can see an example of this [here](https://gist.github.com/habuma/675a4efb4a657391a4b0159e9fda78f5)

This sounds reasonable to me! Also not my area of expertise though (: Happy to review and test if you're able to put something together.

**Comment by cdubz** [comment]
Closed by #9.
